// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzrsrrkfhaulpowrkyej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6cnNycmtmaGF1bHBvd3JreWVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNDExNzAsImV4cCI6MjA3MzgxNzE3MH0.RuB4zhIKqenki_-72LTCCLQg0vVFOGmwQq8BESMkiBo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});